#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/raowl/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
conky -c ~/.fluxbox/styles/Squared\ LMDE\ mod1/.conkyrc &
nm-applet &

#xcompmgr -c &
#cairo-dock &

#/home/rawl/.fluxbox/scripts/screen.sh
#conky -c /home/rawl/.fluxbox/styles/Squared\ LMDE\ mod1/.conkyrc &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/rawl/.fluxbox/log"
fluxbox &
fbpid=$!

sleep 1
{
  # Applications you want to run after fluxbox has started
  # MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN & AT THE END.
  # ipager &
  #gkrellm2 &
  pidgin &
  ~/.fluxbox/scripts/screen.sh &
} &
             
wait $fbpid
